version: '3.8'
services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - ./kagglehub_cache:/root/.cache/kagglehub
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH=/usr/src/app
      - PYTHONUNBUFFERED=1
    working_dir: /usr/src/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
